services:
  - type: web
    name: multigrao-api
    runtime: docker
    dockerfilePath: Multigrao.Api/Dockerfile
    dockerContext: Multigrao.Api
    envVars:
      - key: DB_CONNECTION_STRING
        fromDatabase:
          name: multigrao-db
          property: connectionString
      - key: JWT_KEY
        sync: false
      - key: CORS_ORIGINS
        value: https://multigraos.vercel.app
      - key: MASTER_PASSWORD
        sync: false
      - key: DOTNET_USE_POLLING_FILE_WATCHER
        value: "true"

databases:
  - name: multigrao-db
    plan: free
    databaseName: multigrao_db
