services:
  - type: web
    name: focus-eshop-api
    runtime: docker
    dockerfilePath: FocusEshop.Api/Dockerfile
    dockerContext: FocusEshop.Api
    envVars:
      - key: DB_CONNECTION_STRING
        fromDatabase:
          name: focus-eshop-db
          property: connectionString
      - key: JWT_KEY
        sync: false
      - key: CORS_ORIGINS
        value: https://focus-eshop.vercel.app,https://shop.focus-solutions.tech
      - key: MASTER_PASSWORD
        sync: false
      - key: DOTNET_USE_POLLING_FILE_WATCHER
        value: "true"

databases:
  - name: focus-eshop-db
    plan: free
    databaseName: focus_eshop_db
