export const CORES_DISPONIVEIS: { cor: string; nome: string }[] = [
  { cor: '#0a0a0a', nome: 'Preto' },
  { cor: '#1e293b', nome: 'Slate' },
  { cor: '#475569', nome: 'Cinza' },
  { cor: '#6b7280', nome: 'Cinza claro' },
  { cor: '#1d4ed8', nome: 'Azul marinho' },
  { cor: '#2563eb', nome: 'Azul' },
  { cor: '#0284c7', nome: 'Sky' },
  { cor: '#0891b2', nome: 'Cyan' },
  { cor: '#0d9488', nome: 'Teal' },
  { cor: '#059669', nome: 'Esmeralda' },
  { cor: '#16a34a', nome: 'Verde' },
  { cor: '#65a30d', nome: 'Lima' },
  { cor: '#ca8a04', nome: 'Amarelo' },
  { cor: '#d97706', nome: 'Âmbar' },
  { cor: '#ea580c', nome: 'Laranja' },
  { cor: '#dc2626', nome: 'Vermelho' },
  { cor: '#b91c1c', nome: 'Vermelho escuro' },
  { cor: '#be123c', nome: 'Rose' },
  { cor: '#db2777', nome: 'Rosa' },
  { cor: '#c026d3', nome: 'Fúcsia' },
  { cor: '#9333ea', nome: 'Roxo' },
  { cor: '#7c3aed', nome: 'Violeta' },
  { cor: '#4f46e5', nome: 'Índigo' },
  { cor: '#92400e', nome: 'Marrom' },
  { cor: '#78350f', nome: 'Marrom escuro' },
];
