// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Multigrao.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Multigrao.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260816201835_FreteConfiguracao")]
    partial class FreteConfiguracao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Multigrao.Api.Models.ArquivoUpload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<byte[]>("Conteudo")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("FileName")
                        .IsUnique();

                    b.ToTable("ArquivosUpload");
                });

            modelBuilder.Entity("Multigrao.Api.Models.AtendimentoLead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ConversaId")
                        .HasColumnType("integer");

                    b.Property<string>("Embalagem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<bool>("IAAtiva")
                        .HasColumnType("boolean");

                    b.Property<string>("Interesse")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Pagamento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("PedidoId")
                        .HasColumnType("integer");

                    b.Property<string>("Quantidade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ResumoIA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TipoCliente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("UsuarioAtendenteId")
                        .HasColumnType("integer");

                    b.Property<bool>("VendaFechada")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ConversaId");

                    b.HasIndex("PedidoId");

                    b.HasIndex("UsuarioAtendenteId");

                    b.ToTable("AtendimentoLeads");
                });

            modelBuilder.Entity("Multigrao.Api.Models.Aviso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AutorId")
                        .HasColumnType("integer");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataPublicacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<int?>("SetorAlvoId")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("SetorAlvoId");

                    b.ToTable("Avisos");
                });

            modelBuilder.Entity("Multigrao.Api.Models.Carrinho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CpfCnpj")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "CpfCnpj")
                        .IsUnique();

                    b.ToTable("Carrinhos");
                });

            modelBuilder.Entity("Multigrao.Api.Models.CarrinhoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CarrinhoId")
                        .HasColumnType("integer");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CarrinhoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("CarrinhoItens");
                });

            modelBuilder.Entity("Multigrao.Api.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("Multigrao.Api.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("BloqueadoFinanceiro")
                        .HasColumnType("boolean");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CpfCnpj")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("InscricaoEstadual")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("InscricaoMunicipal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RazaoSocialNome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("RegimeTributario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TipoPessoa")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<int?>("VendedorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VendedorId");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bairro = "Boa Viagem",
                            BloqueadoFinanceiro = false,
                            Cep = "",
                            Cidade = "Recife",
                            Complemento = "",
                            CpfCnpj = "12.345.678/0001-90",
                            Email = "contato@paodourado.com.br",
                            EmpresaId = 1,
                            Estado = "PE",
                            InscricaoEstadual = "",
                            InscricaoMunicipal = "",
                            Logradouro = "",
                            NomeFantasia = "",
                            Numero = "",
                            RazaoSocialNome = "Padaria Pão Dourado",
                            RegimeTributario = "",
                            Telefone = "(81) 3333-4444",
                            TipoPessoa = "PJ"
                        },
                        new
                        {
                            Id = 2,
                            Bairro = "Casa Forte",
                            BloqueadoFinanceiro = false,
                            Cep = "",
                            Cidade = "Recife",
                            Complemento = "",
                            CpfCnpj = "98.765.432/0001-10",
                            Email = "compras@fresh.com.br",
                            EmpresaId = 1,
                            Estado = "PE",
                            InscricaoEstadual = "",
                            InscricaoMunicipal = "",
                            Logradouro = "",
                            NomeFantasia = "",
                            Numero = "",
                            RazaoSocialNome = "Supermercado Fresh",
                            RegimeTributario = "",
                            Telefone = "(81) 3333-5555",
                            TipoPessoa = "PJ"
                        },
                        new
                        {
                            Id = 3,
                            Bairro = "Aflitos",
                            BloqueadoFinanceiro = false,
                            Cep = "",
                            Cidade = "Recife",
                            Complemento = "",
                            CpfCnpj = "11.222.333/0001-44",
                            Email = "vendas@naturalzinha.com.br",
                            EmpresaId = 1,
                            Estado = "PE",
                            InscricaoEstadual = "",
                            InscricaoMunicipal = "",
                            Logradouro = "",
                            NomeFantasia = "",
                            Numero = "",
                            RazaoSocialNome = "Loja Naturalzinha",
                            RegimeTributario = "",
                            Telefone = "(81) 3333-6666",
                            TipoPessoa = "PJ"
                        });
                });

            modelBuilder.Entity("Multigrao.Api.Models.ConfiguracaoSistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Bairro")
                        .HasColumnType("text");

                    b.Property<string>("Cep")
                        .HasColumnType("text");

                    b.Property<string>("Cidade")
                        .HasColumnType("text");

                    b.Property<string>("Cnpj")
                        .HasColumnType("text");

                    b.Property<string>("CorFonte")
                        .HasColumnType("text");

                    b.Property<string>("CorPrincipal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorSecundaria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DesignEcommerce")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Endereco")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .HasColumnType("text");

                    b.Property<bool>("ExibirNomeAbaixoLogo")
                        .HasColumnType("boolean");

                    b.Property<string>("Fonte")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("FreteAtivo")
                        .HasColumnType("boolean");

                    b.Property<string>("HeroImagemTipo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("produto");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<string>("LinksBio")
                        .HasColumnType("text");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Logradouro")
                        .HasColumnType("text");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("MascoteUrl")
                        .HasColumnType("text");

                    b.Property<string>("NomeEmpresa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Numero")
                        .HasColumnType("text");

                    b.Property<string>("Redirecionamentos")
                        .HasColumnType("text");

                    b.Property<string>("Slogan")
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubtextoHero")
                        .HasColumnType("text");

                    b.Property<string>("TipoCarrinho")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoMenu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TituloHero")
                        .HasColumnType("text");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracoesSistema");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Bairro = "Centro",
                            Cidade = "Paulista",
                            Cnpj = "26.277.355/0001-70",
                            CorPrincipal = "#0a0a0a",
                            CorSecundaria = "#f97316",
                            DesignEcommerce = "claro",
                            Endereco = "Centro — Paulista — PE",
                            Estado = "PE",
                            ExibirNomeAbaixoLogo = true,
                            Fonte = "classica",
                            FreteAtivo = false,
                            HeroImagemTipo = "produto",
                            LogoUrl = "/multigraos-logo.png",
                            NomeEmpresa = "Multigrãos",
                            Slogan = "Amendoim & Especiarias",
                            Slug = "multigraos",
                            TipoCarrinho = "pagina",
                            TipoMenu = "dock",
                            VideoUrl = "/multigraosvid.mp4"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Cidade = "Paulista",
                            Cnpj = "00.000.000/0000-00",
                            CorPrincipal = "#111827",
                            CorSecundaria = "#f97316",
                            DesignEcommerce = "claro",
                            Endereco = "Paulista — PE",
                            Estado = "PE",
                            ExibirNomeAbaixoLogo = true,
                            Fonte = "classica",
                            FreteAtivo = false,
                            HeroImagemTipo = "produto",
                            LogoUrl = "/multigraos-logo.png",
                            NomeEmpresa = "Focus Solutions",
                            Slogan = "Plataforma de Gestão",
                            Slug = "focus",
                            TipoCarrinho = "pagina",
                            TipoMenu = "dock"
                        });
                });

            modelBuilder.Entity("Multigrao.Api.Models.Contato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Contatos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cargo = "",
                            ClienteId = 1,
                            Email = "",
                            EmpresaId = 1,
                            Nome = "Carlos Eduardo",
                            Telefone = "(81) 99812-3344"
                        },
                        new
                        {
                            Id = 2,
                            Cargo = "",
                            ClienteId = 1,
                            Email = "",
                            EmpresaId = 1,
                            Nome = "Fernanda Lima",
                            Telefone = "(81) 99766-5588"
                        },
                        new
                        {
                            Id = 3,
                            Cargo = "",
                            ClienteId = 2,
                            Email = "",
                            EmpresaId = 1,
                            Nome = "Roberto Alves",
                            Telefone = "(81) 99234-1122"
                        },
                        new
                        {
                            Id = 4,
                            Cargo = "",
                            ClienteId = 2,
                            Email = "",
                            EmpresaId = 1,
                            Nome = "Mariana Costa",
                            Telefone = "(81) 99100-2233"
                        },
                        new
                        {
                            Id = 5,
                            Cargo = "",
                            ClienteId = 3,
                            Email = "",
                            EmpresaId = 1,
                            Nome = "Pedro Henrique",
                            Telefone = "(81) 98877-6655"
                        },
                        new
                        {
                            Id = 6,
                            Cargo = "",
                            Email = "",
                            EmpresaId = 1,
                            Nome = "Ana Beatriz",
                            Telefone = "(81) 98543-2211"
                        },
                        new
                        {
                            Id = 7,
                            Cargo = "",
                            Email = "",
                            EmpresaId = 1,
                            Nome = "Lucas Nascimento",
                            Telefone = "(81) 98432-1100"
                        });
                });

            modelBuilder.Entity("Multigrao.Api.Models.Conversa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Conversas");
                });

            modelBuilder.Entity("Multigrao.Api.Models.Enquete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean");

                    b.Property<int>("AutorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataExpiracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.ToTable("Enquetes");
                });

            modelBuilder.Entity("Multigrao.Api.Models.Entrega", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<string>("MotivoDevolucao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<int>("RotaId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("RotaId");

                    b.ToTable("Entregas");
                });

            modelBuilder.Entity("Multigrao.Api.Models.EntregaPedido", b =>
                {
                    b.Property<int>("EntregaId")
                        .HasColumnType("integer");

                    b.Property<int>("PedidoId")
                        .HasColumnType("integer");

                    b.HasKey("EntregaId", "PedidoId");

                    b.HasIndex("PedidoId");

                    b.ToTable("EntregasPedidos");
                });

            modelBuilder.Entity("Multigrao.Api.Models.FaixaFrete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AteKm")
                        .HasColumnType("numeric");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("FaixasFrete");
                });

            modelBuilder.Entity("Multigrao.Api.Models.ItemPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<int>("PedidoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PesoUnitario")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("numeric");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("numeric");

                    b.Property<bool>("Separado")
                        .HasColumnType("boolean");

                    b.Property<int?>("SeparadoPorUsuarioId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("SeparadoPorUsuarioId");

                    b.ToTable("ItensPedido");
                });

            modelBuilder.Entity("Multigrao.Api.Models.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cor")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<byte[]>("ImagemBytes")
                        .HasColumnType("bytea");

                    b.Property<string>("ImagemContentType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ImagemUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Marcas");
                });

            modelBuilder.Entity("Multigrao.Api.Models.Mensagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConversaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataVisualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UrlAnexo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UsuarioRemetenteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConversaId");

                    b.HasIndex("UsuarioRemetenteId");

                    b.ToTable("Mensagens");
                });

            modelBuilder.Entity("Multigrao.Api.Models.Notificacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<bool>("Lida")
                        .HasColumnType("boolean");

                    b.Property<string>("Link")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SetorAlvo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("UsuarioDestinoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Notificacoes");
                });

            modelBuilder.Entity("Multigrao.Api.Models.OpcaoEnquete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<int>("EnqueteId")
                        .HasColumnType("integer");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("EnqueteId");

                    b.ToTable("OpcoesEnquete");
                });

            modelBuilder.Entity("Multigrao.Api.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Acrescimo")
                        .HasColumnType("numeric");

                    b.Property<string>("Bairro")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Cep")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CpfCnpj")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Desconto")
                        .HasColumnType("numeric");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<bool>("EnderecoConfere")
                        .HasColumnType("boolean");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<bool>("LiberadoFinanceiro")
                        .HasColumnType("boolean");

                    b.Property<string>("Logradouro")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Numero")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Pagamento")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("PesoTotal")
                        .HasColumnType("numeric");

                    b.Property<int?>("PrazoPagamentoDias")
                        .HasColumnType("integer");

                    b.Property<string>("SolicitanteNome")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SolicitanteTelefone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TipoEntrega")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("ValorFinal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("Multigrao.Api.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<string>("CodigoERP")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("Destaque")
                        .HasColumnType("boolean");

                    b.Property<string>("Embalagem")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Estoque")
                        .HasColumnType("numeric");

                    b.Property<byte[]>("ImagemBytes")
                        .HasColumnType("bytea");

                    b.Property<string>("ImagemContentType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ImagemUrl")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("MarcaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("PesoUnidade")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PrecoAtacado")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PrecoVarejo")
                        .HasColumnType("numeric");

                    b.Property<decimal>("QuantidadeMinimaAtacado")
                        .HasColumnType("numeric");

                    b.Property<string>("UnidadeVenda")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("ValorFrete")
                        .HasColumnType("numeric");

                    b.Property<bool>("VendidoAGranel")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("MarcaId");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            CodigoERP = "CAS001",
                            Destaque = false,
                            EmpresaId = 1,
                            Estoque = 0m,
                            Nome = "Castanha do Pará",
                            PesoUnidade = 0.5m,
                            PrecoAtacado = 0m,
                            PrecoVarejo = 0m,
                            QuantidadeMinimaAtacado = 5m,
                            ValorFrete = 0m,
                            VendidoAGranel = false
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            CodigoERP = "CHI001",
                            Destaque = false,
                            EmpresaId = 1,
                            Estoque = 0m,
                            Nome = "Chia (1kg)",
                            PesoUnidade = 1m,
                            PrecoAtacado = 0m,
                            PrecoVarejo = 0m,
                            QuantidadeMinimaAtacado = 5m,
                            ValorFrete = 0m,
                            VendidoAGranel = false
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            CodigoERP = "AVE001",
                            Destaque = false,
                            EmpresaId = 1,
                            Estoque = 0m,
                            Nome = "Aveia em Flocos",
                            PesoUnidade = 0.5m,
                            PrecoAtacado = 0m,
                            PrecoVarejo = 0m,
                            QuantidadeMinimaAtacado = 5m,
                            ValorFrete = 0m,
                            VendidoAGranel = false
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            CodigoERP = "QUI001",
                            Destaque = false,
                            EmpresaId = 1,
                            Estoque = 0m,
                            Nome = "Quinoa (500g)",
                            PesoUnidade = 0.5m,
                            PrecoAtacado = 0m,
                            PrecoVarejo = 0m,
                            QuantidadeMinimaAtacado = 5m,
                            ValorFrete = 0m,
                            VendidoAGranel = false
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            CodigoERP = "LIN001",
                            Destaque = false,
                            EmpresaId = 1,
                            Estoque = 0m,
                            Nome = "Linhaça Dourada",
                            PesoUnidade = 0.25m,
                            PrecoAtacado = 0m,
                            PrecoVarejo = 0m,
                            QuantidadeMinimaAtacado = 5m,
                            ValorFrete = 0m,
                            VendidoAGranel = false
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            CodigoERP = "NOZ001",
                            Destaque = false,
                            EmpresaId = 1,
                            Estoque = 0m,
                            Nome = "Nozes (500g)",
                            PesoUnidade = 0.5m,
                            PrecoAtacado = 0m,
                            PrecoVarejo = 0m,
                            QuantidadeMinimaAtacado = 5m,
                            ValorFrete = 0m,
                            VendidoAGranel = false
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            CodigoERP = "AME001",
                            Destaque = false,
                            EmpresaId = 1,
                            Estoque = 0m,
                            Nome = "Amêndoas (250g)",
                            PesoUnidade = 0.25m,
                            PrecoAtacado = 0m,
                            PrecoVarejo = 0m,
                            QuantidadeMinimaAtacado = 5m,
                            ValorFrete = 0m,
                            VendidoAGranel = false
                        },
                        new
                        {
                            Id = 8,
                            Ativo = true,
                            CodigoERP = "CAC001",
                            Destaque = false,
                            EmpresaId = 1,
                            Estoque = 0m,
                            Nome = "Cacau em Pó",
                            PesoUnidade = 0.3m,
                            PrecoAtacado = 0m,
                            PrecoVarejo = 0m,
                            QuantidadeMinimaAtacado = 5m,
                            ValorFrete = 0m,
                            VendidoAGranel = false
                        });
                });

            modelBuilder.Entity("Multigrao.Api.Models.Promocao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Promocoes");
                });

            modelBuilder.Entity("Multigrao.Api.Models.PromocaoProduto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PrecoPromocional")
                        .HasColumnType("numeric");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer");

                    b.Property<int>("PromocaoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("PromocaoId");

                    b.ToTable("PromocoesProduto");
                });

            modelBuilder.Entity("Multigrao.Api.Models.Rota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<string>("LinkGoogleMaps")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MotoristaId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("VeiculoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MotoristaId");

                    b.HasIndex("VeiculoId");

                    b.ToTable("Rotas");
                });

            modelBuilder.Entity("Multigrao.Api.Models.Setor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Setores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Comercial"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Separação"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Logística"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Conferência"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Entregas"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Compras"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Vendedor"
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Financeiro"
                        });
                });

            modelBuilder.Entity("Multigrao.Api.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsuarioLogin")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            EmpresaId = 1,
                            Nome = "Admin Multigrãos",
                            Role = "AdminMaster",
                            SenhaHash = "$2a$11$9tpv10peRM0MqlDYoaqhDeVEnG04k8PxomSXoA2qGVL8q01aM4xvq",
                            UsuarioLogin = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            EmpresaId = 1,
                            Nome = "João Comercial",
                            Role = "Comum",
                            SenhaHash = "$2a$11$9tpv10peRM0MqlDYoaqhDeVEnG04k8PxomSXoA2qGVL8q01aM4xvq",
                            UsuarioLogin = "joao"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            EmpresaId = 1,
                            Nome = "Ana Separação",
                            Role = "Comum",
                            SenhaHash = "$2a$11$9tpv10peRM0MqlDYoaqhDeVEnG04k8PxomSXoA2qGVL8q01aM4xvq",
                            UsuarioLogin = "ana"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            EmpresaId = 1,
                            Nome = "Pedro Motorista",
                            Role = "Comum",
                            SenhaHash = "$2a$11$9tpv10peRM0MqlDYoaqhDeVEnG04k8PxomSXoA2qGVL8q01aM4xvq",
                            UsuarioLogin = "pedro"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            EmpresaId = 2,
                            Nome = "Admin Focus",
                            Role = "AdminMaster",
                            SenhaHash = "$2a$11$8txlZeWbLmAkE.FUvRPhj.P6VzpU7K2GVhfVMWMJKqVldAuGhvEXC",
                            UsuarioLogin = "focus"
                        });
                });

            modelBuilder.Entity("Multigrao.Api.Models.UsuarioSetor", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("SetorId")
                        .HasColumnType("integer");

                    b.HasKey("UsuarioId", "SetorId");

                    b.HasIndex("SetorId");

                    b.ToTable("UsuarioSetores");

                    b.HasData(
                        new
                        {
                            UsuarioId = 1,
                            SetorId = 1
                        },
                        new
                        {
                            UsuarioId = 2,
                            SetorId = 1
                        },
                        new
                        {
                            UsuarioId = 2,
                            SetorId = 3
                        },
                        new
                        {
                            UsuarioId = 3,
                            SetorId = 2
                        },
                        new
                        {
                            UsuarioId = 4,
                            SetorId = 3
                        },
                        new
                        {
                            UsuarioId = 4,
                            SetorId = 5
                        });
                });

            modelBuilder.Entity("Multigrao.Api.Models.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("PesoMaximo")
                        .HasColumnType("numeric");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Veiculos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmpresaId = 1,
                            Modelo = "Fiorino",
                            PesoMaximo = 800m,
                            Placa = "ABC-1234"
                        },
                        new
                        {
                            Id = 2,
                            EmpresaId = 1,
                            Modelo = "Van Master",
                            PesoMaximo = 1500m,
                            Placa = "DEF-5678"
                        });
                });

            modelBuilder.Entity("Multigrao.Api.Models.VotoEnquete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataVoto")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<int>("EnqueteId")
                        .HasColumnType("integer");

                    b.Property<int>("OpcaoEnqueteId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EnqueteId");

                    b.HasIndex("OpcaoEnqueteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("VotosEnquete");
                });

            modelBuilder.Entity("Multigrao.Api.Models.AtendimentoLead", b =>
                {
                    b.HasOne("Multigrao.Api.Models.Conversa", "Conversa")
                        .WithMany()
                        .HasForeignKey("ConversaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Multigrao.Api.Models.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Multigrao.Api.Models.Usuario", "UsuarioAtendente")
                        .WithMany()
                        .HasForeignKey("UsuarioAtendenteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Conversa");

                    b.Navigation("Pedido");

                    b.Navigation("UsuarioAtendente");
                });

            modelBuilder.Entity("Multigrao.Api.Models.Aviso", b =>
                {
                    b.HasOne("Multigrao.Api.Models.Usuario", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Multigrao.Api.Models.Setor", "SetorAlvo")
                        .WithMany()
                        .HasForeignKey("SetorAlvoId");

                    b.Navigation("Autor");

                    b.Navigation("SetorAlvo");
                });

            modelBuilder.Entity("Multigrao.Api.Models.CarrinhoItem", b =>
                {
                    b.HasOne("Multigrao.Api.Models.Carrinho", "Carrinho")
                        .WithMany("Itens")
                        .HasForeignKey("CarrinhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Multigrao.Api.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrinho");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Multigrao.Api.Models.Cliente", b =>
                {
                    b.HasOne("Multigrao.Api.Models.Usuario", "Vendedor")
                        .WithMany("ClientesVendedor")
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("Multigrao.Api.Models.Contato", b =>
                {
                    b.HasOne("Multigrao.Api.Models.Cliente", "Cliente")
                        .WithMany("Contatos")
                        .HasForeignKey("ClienteId");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Multigrao.Api.Models.Conversa", b =>
                {
                    b.HasOne("Multigrao.Api.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Multigrao.Api.Models.Enquete", b =>
                {
                    b.HasOne("Multigrao.Api.Models.Usuario", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("Multigrao.Api.Models.Entrega", b =>
                {
                    b.HasOne("Multigrao.Api.Models.Rota", "Rota")
                        .WithMany("Entregas")
                        .HasForeignKey("RotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rota");
                });

            modelBuilder.Entity("Multigrao.Api.Models.EntregaPedido", b =>
                {
                    b.HasOne("Multigrao.Api.Models.Entrega", "Entrega")
                        .WithMany("EntregaPedidos")
                        .HasForeignKey("EntregaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Multigrao.Api.Models.Pedido", "Pedido")
                        .WithMany("EntregaPedidos")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entrega");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Multigrao.Api.Models.ItemPedido", b =>
                {
                    b.HasOne("Multigrao.Api.Models.Pedido", "Pedido")
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Multigrao.Api.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Multigrao.Api.Models.Usuario", "SeparadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("SeparadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Pedido");

                    b.Navigation("Produto");

                    b.Navigation("SeparadoPorUsuario");
                });

            modelBuilder.Entity("Multigrao.Api.Models.Mensagem", b =>
                {
                    b.HasOne("Multigrao.Api.Models.Conversa", "Conversa")
                        .WithMany("Mensagens")
                        .HasForeignKey("ConversaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Multigrao.Api.Models.Usuario", "UsuarioRemetente")
                        .WithMany()
                        .HasForeignKey("UsuarioRemetenteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Conversa");

                    b.Navigation("UsuarioRemetente");
                });

            modelBuilder.Entity("Multigrao.Api.Models.OpcaoEnquete", b =>
                {
                    b.HasOne("Multigrao.Api.Models.Enquete", "Enquete")
                        .WithMany("Opcoes")
                        .HasForeignKey("EnqueteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enquete");
                });

            modelBuilder.Entity("Multigrao.Api.Models.Pedido", b =>
                {
                    b.HasOne("Multigrao.Api.Models.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("ClienteId");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Multigrao.Api.Models.Produto", b =>
                {
                    b.HasOne("Multigrao.Api.Models.Categoria", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Multigrao.Api.Models.Marca", "Marca")
                        .WithMany("Produtos")
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Categoria");

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("Multigrao.Api.Models.PromocaoProduto", b =>
                {
                    b.HasOne("Multigrao.Api.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Multigrao.Api.Models.Promocao", "Promocao")
                        .WithMany("Produtos")
                        .HasForeignKey("PromocaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("Promocao");
                });

            modelBuilder.Entity("Multigrao.Api.Models.Rota", b =>
                {
                    b.HasOne("Multigrao.Api.Models.Usuario", "Motorista")
                        .WithMany()
                        .HasForeignKey("MotoristaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Multigrao.Api.Models.Veiculo", "Veiculo")
                        .WithMany()
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Motorista");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("Multigrao.Api.Models.UsuarioSetor", b =>
                {
                    b.HasOne("Multigrao.Api.Models.Setor", "Setor")
                        .WithMany("UsuarioSetores")
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Multigrao.Api.Models.Usuario", "Usuario")
                        .WithMany("UsuarioSetores")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Setor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Multigrao.Api.Models.VotoEnquete", b =>
                {
                    b.HasOne("Multigrao.Api.Models.Enquete", "Enquete")
                        .WithMany("Votos")
                        .HasForeignKey("EnqueteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Multigrao.Api.Models.OpcaoEnquete", "OpcaoEnquete")
                        .WithMany()
                        .HasForeignKey("OpcaoEnqueteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Multigrao.Api.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enquete");

                    b.Navigation("OpcaoEnquete");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Multigrao.Api.Models.Carrinho", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Multigrao.Api.Models.Categoria", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("Multigrao.Api.Models.Cliente", b =>
                {
                    b.Navigation("Contatos");

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("Multigrao.Api.Models.Conversa", b =>
                {
                    b.Navigation("Mensagens");
                });

            modelBuilder.Entity("Multigrao.Api.Models.Enquete", b =>
                {
                    b.Navigation("Opcoes");

                    b.Navigation("Votos");
                });

            modelBuilder.Entity("Multigrao.Api.Models.Entrega", b =>
                {
                    b.Navigation("EntregaPedidos");
                });

            modelBuilder.Entity("Multigrao.Api.Models.Marca", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("Multigrao.Api.Models.Pedido", b =>
                {
                    b.Navigation("EntregaPedidos");

                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Multigrao.Api.Models.Promocao", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("Multigrao.Api.Models.Rota", b =>
                {
                    b.Navigation("Entregas");
                });

            modelBuilder.Entity("Multigrao.Api.Models.Setor", b =>
                {
                    b.Navigation("UsuarioSetores");
                });

            modelBuilder.Entity("Multigrao.Api.Models.Usuario", b =>
                {
                    b.Navigation("ClientesVendedor");

                    b.Navigation("UsuarioSetores");
                });
#pragma warning restore 612, 618
        }
    }
}
